In [2]:
import numpy as np
t = 'latences_2106_initial_batch_1_KNN_Subsampling_1_percentage.txt'

In [2]:
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

In [3]:
import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

True
100000


In [4]:
k = 4                          # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.175174  7.2076287 7.251163 ]
 [0.        6.323565  6.684582  6.799944 ]
 [0.        5.7964087 6.3917365 7.2815127]
 [0.        7.277905  7.5279875 7.6628447]
 [0.        6.763804  7.295122  7.368814 ]]
[[ 381  207  210  477]
 [ 526  911  142   72]
 [ 838  527 1290  425]
 [ 196  184  164  359]
 [ 526  377  120  425]]
[[ 9900 10500  9309  9831]
 [11055 10895 10812 11321]
 [11353 11103 10164  9787]
 [10571 10664 10632  9638]
 [ 9628  9554 10036  9582]]


In [7]:
import torch

In [13]:
torch.ones(3,64,64).unsqueeze(0).size()

torch.Size([1, 3, 64, 64])

In [6]:
a = [(1,2),(12,4),(4,1)]
for k, (l, j) in enumerate(a):
    print(k)
    print(l)

0
1
1
12
2
4


In [6]:
a = int(1e6)

In [9]:
from enum import Enum
class Acceler(Enum):
    gpu = 1
    cpu = 2

In [11]:
Acceler(1).name

'gpu'

In [13]:
import timeit
%%timeit -r5 -n10
# find sum to first 1 million numbers
sum_x = 0
for i in range(1000000):
    sum_x += i

UsageError: Line magic function `%%timeit` not found.


In [14]:
float(1)

1.0

In [15]:
1e3

1000.0

In [17]:
warm_up = 10
for _ in range(warm_up):
    print('FCK')

FCK
FCK
FCK
FCK
FCK
FCK
FCK
FCK
FCK
FCK
