In [6]:
import numpy as np
import pandas as pd
t = 'latences_2106_initial_batch_1_KNN_Subsampling_1_percentage.txt'

In [4]:
import pickle
objects = []
path = ".\\embeddings\\carpet\\embedding.pickle"
with (open(path, "rb")) as openfile:
    while True:
        try:
            objects.append(pickle.load(openfile))
        except EOFError:
            break

In [8]:
objects[0].shape

(219, 1536)

In [ ]:
torch.

In [20]:
a = pd.read_csv('.\\results\\csv\\1234.csv', index_col=0)

In [21]:
res = 0.90
new_row = np.array([res]*a.shape[0])
new_row_pd = pd.DataFrame({"img_auc": new_row})

In [22]:
new_row_pd

img_auc
0      0.9
1      0.9
2      0.9
3      0.9

In [23]:
pd.concat([a, new_row_pd], axis=1)

#1 feature extraction cpu  #2 feature extraction gpu  \
0                   0.071850                   0.380694   
1                   0.070729                   0.520765   
2                   0.071019                   0.403751   
3                   0.080271                   0.542230   

   #3 embedding of features cpu  #4 embedding of features gpu  \
0                      0.534967                      0.227191   
1                      0.696608                      0.247636   
2                      0.566768                      0.235073   
3                      0.708157                      0.247286   

   #5 search with memory bank cpu  #6 search with memory bank gpu  \
0                        0.242007                        0.241840   
1                        0.240538                        0.240348   
2                        0.240014                        0.239839   
3                        0.240345                        0.240124   

   #7 anomaly map cpu  #8 anomaly map gpu  #9 sum cpu  #10 sum gpu  \
0            0.953473            0.954173    1.802298     1.803898   
1            0.944339            0.945044    1.952215     1.953793   
2            0.960378            0.960914    1.838178     1.839577   
3            1.019501            1.020211    2.048275     2.049851   

   #11 whole process cpu  #12 whole process gpu  #13 preparation memory bank  \
0               1.814195               1.814264                      4.31682   
1               1.964618               1.964702                      4.31682   
2               1.849678               1.849783                      4.31682   
3               2.061186               2.061302                      4.31682   

   batch_size  input_size  coreset_sampling_ratio  n_neighbors  \
0          56          64                    0.01            9   
1          56          64                    0.01            9   
2          56          64                    0.01            9   
3          56          64                    0.01            9   

                                      patch_size  resulting_features  img_auc  
0  AvgPool2d(kernel_size=3, stride=1, padding=1)                 256      0.9  
1  AvgPool2d(kernel_size=3, stride=1, padding=1)                 256      0.9  
2  AvgPool2d(kernel_size=3, stride=1, padding=1)                 256      0.9  
3  AvgPool2d(kernel_size=3, stride=1, padding=1)                 256      0.9

In [2]:
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

In [3]:
import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

True
100000


In [4]:
k = 4                          # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.175174  7.2076287 7.251163 ]
 [0.        6.323565  6.684582  6.799944 ]
 [0.        5.7964087 6.3917365 7.2815127]
 [0.        7.277905  7.5279875 7.6628447]
 [0.        6.763804  7.295122  7.368814 ]]
[[ 381  207  210  477]
 [ 526  911  142   72]
 [ 838  527 1290  425]
 [ 196  184  164  359]
 [ 526  377  120  425]]
[[ 9900 10500  9309  9831]
 [11055 10895 10812 11321]
 [11353 11103 10164  9787]
 [10571 10664 10632  9638]
 [ 9628  9554 10036  9582]]


In [2]:
import torch

In [11]:
a = torch.nn.AvgPool3d(kernel_size=3, stride=(2,1,1), padding=0)
b = torch.ones(12,32,64,64)

In [12]:
a(b).size()

torch.Size([12, 15, 62, 62])

In [6]:
a = [(1,2),(12,4),(4,1)]
for k, (l, j) in enumerate(a):
    print(k)
    print(l)

0
1
1
12
2
4


In [6]:
a = int(1e6)

In [9]:
from enum import Enum
class Acceler(Enum):
    gpu = 1
    cpu = 2

In [11]:
Acceler(1).name

'gpu'

In [13]:
import timeit
%%timeit -r5 -n10
# find sum to first 1 million numbers
sum_x = 0
for i in range(1000000):
    sum_x += i

UsageError: Line magic function `%%timeit` not found.


In [14]:
float(1)

1.0

In [15]:
1e3

1000.0

In [17]:
warm_up = 10
for _ in range(warm_up):
    print('FCK')

FCK
FCK
FCK
FCK
FCK
FCK
FCK
FCK
FCK
FCK
